[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
lib_deps =
    fortyseveneffects/MIDI Library
    marcoschwartz/LiquidCrystal_I2C
    paulstoffregen/Encoder

