[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
extra_scripts = pre:tools/build_demos.py   ; demos/*.json -> src/sequencer/demos_data.h
lib_deps =
    fortyseveneffects/MIDI Library
    marcoschwartz/LiquidCrystal_I2C
    paulstoffregen/Encoder
    teemuatlut/TMCStepper

[env:teensy41_test_hall]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
test_filter = test_hall
build_src_filter = -<*>

[env:teensy41_test_stepper]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_stepper
lib_deps =
    teemuatlut/TMCStepper

[env:teensy41_test_uart]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_uart

[env:teensy41_test_midi]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
test_filter = test_midi
lib_deps =
    fortyseveneffects/MIDI Library
    marcoschwartz/LiquidCrystal_I2C
    paulstoffregen/Encoder

[env:teensy41_test_ui]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_ui
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    paulstoffregen/Encoder

[env:teensy41_test_hall_z]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_hall_z

[env:teensy41_test_hall_range]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_hall_range

[env:teensy41_test_hall_noise]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41 -Isrc
test_framework = unity
build_src_filter = -<*> +<motion/stepper.cpp> +<motion/platter.cpp>
test_build_src = yes
test_filter = test_hall_noise
lib_deps =
    teemuatlut/TMCStepper

[env:teensy41_test_stepper_wiring]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_stepper_wiring
lib_deps =
    teemuatlut/TMCStepper

[env:teensy41_test_eeprom_erase]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_eeprom_erase
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    teemuatlut/TMCStepper

[env:teensy41_test_i2c_audio]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DTEENSY41
test_framework = unity
build_src_filter = -<*>
test_filter = test_i2c_audio
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
